version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${SENHA_DB}
      POSTGRES_USER: ${USER_ADMIN}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ${SET_VOLUME}

#  adminer:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"
#    ports:
#      - 5080:80
#    depends_on:
#      - db